---
title: "Patient08 Differentially Expanded Tumor-blood Clonotypes"
author: "Gerard Deuner Cos"
date: "2024-05-05"
output: html_document
---

```{r}
# load libraries
library(Seurat)
library(dplyr)
library(scRepertoire)
library(SeuratData)
library(SeuratDisk)
library(rhdf5)
library(scCustomize)
library(stringr)
library(ggplot2)
library(ggpubr)
library(gridExtra)
library(qs)
```

```{r}
# import path variables 
source("/Users/gerarddeunercos/Documents/cluster1/gdeuner/config.R")
```

```{r}
# read tumor TCR files and match it to RNA data
P08_S1 <- read.csv(paste0(sp.proj.dir, "/data/SERPENTINE_22_23/jobs/SPE_1_08_SCR_A_FRESH/SPE_1_08_SCR_A_FRESH/outs/per_sample_outs/SPE_1_08_SCR_A_FRESH/vdj_t/filtered_contig_annotations.csv"))
P08_S2 <- read.csv(paste0(sp.proj.dir, "/data/SERPENTINE_30_31/jobs/SPE_1_8_C2_A_FRESH_1/SPE_1_8_C2_A_FRESH_1/outs/per_sample_outs/SPE_1_8_C2_A_FRESH_1/vdj_t/filtered_contig_annotations.csv"))
P08_S4 <- read.csv(paste0(sp.proj.dir, "/data/SERPENTINE_30_31/jobs/SPE_1_8_C2_A_FRESH_2/SPE_1_8_C2_A_FRESH_2/outs/per_sample_outs/SPE_1_8_C2_A_FRESH_2/vdj_t/filtered_contig_annotations.csv"))


contig_list_TCR <- list(P08_S1, P08_S2,         P08_S4)
                        

combined_tcr <- combineTCR(contig_list_TCR, 
                ID = c(
                  "SPE_1_08_SCR_A_FRESH", "SPE_1_8_C2_A_FRESH_1", "SPE_1_8_C2_A_FRESH_2"
                  ), 
                samples = c(
                  "SERPENTINE_22_23", "SERPENTINE_30_31", "SERPENTINE_30_31"
                  )
                )

combined_tcr$SERPENTINE_22_23_SPE_1_08_SCR_A_FRESH$barcode <- str_remove_all(combined_tcr$SERPENTINE_22_23_SPE_1_08_SCR_A_FRESH$barcode, pattern = "-1$|-2$|-3$")
combined_tcr$SERPENTINE_30_31_SPE_1_8_C2_A_FRESH_1$barcode <- str_remove_all(combined_tcr$SERPENTINE_30_31_SPE_1_8_C2_A_FRESH_1$barcode, pattern = "-1$|-2$|-3$")
combined_tcr$SERPENTINE_30_31_SPE_1_8_C2_A_FRESH_2$barcode <- str_remove_all(combined_tcr$SERPENTINE_30_31_SPE_1_8_C2_A_FRESH_2$barcode, pattern = "-1$|-2$|-3$")

combined.TCR <- combined_tcr
```

```{r}
# load P08 preprocessed seurat object
p08.data <- qread("/Users/gerarddeunercos/Downloads/Combined_SCR_C02_T_TCR_05-05-24.qs")
```

```{r}
## adjust seurat object's cell barcoodes so they match the combined.TCR barcodes
#cell.barcodes <- rownames(data[[]])
#cell.barcodes <- stringr::str_split(cell.barcodes, "_", simplify = TRUE, n = 2)[, 2]
#data <- RenameCells(data, new.names = cell.barcodes)
```

```{r}
# Combine Expression - join RNA + TCR data
data <- combineExpression(
  combined.TCR, 
  p08.data, 
  chain = "both",
  cloneCall="nt", 
  proportion = FALSE, 
  cloneSize=c(Single=1, Small=5, Medium=20, Large=50, Hyperexpanded=100))
```

```{r}
# separate alpha and beta chains
head(p08.data@meta.data$CTnt) # combined expression using both chains, therefore we need to split them between alpha and beta chain
p08.data$CTnt_TRA <- substr(p08.data@meta.data$CTnt, 1, regexpr("_", data@meta.data$CTnt) - 1)
p08.data$CTnt_TRB <- sub(".*_", "", p08.data@meta.data$CTnt)
```


```{r}
# save p08 seurat object with updated TCR data
#qsave(data, "/Users/gerarddeunercos/Documents/cluster1/gdeuner/SERPENTINE/data/outputdata/Patient_08/Patient_08_TCR_updated_06-05-24.qs")
qsave(p08.data, "/Users/gerarddeunercos/Downloads/Patient_08_TCR_updated_06-05-24.qs")
#qread(p08.data, "/Users/gerarddeunercos/Downloads/Patient_08_TCR_updated_06-05-24.qs")
```

```{r}
# read annotated 2.0 combined seurat object
data <- qread("/Users/gerarddeunercos/Downloads/Combined_SCR_C02_T_TCR_05-05-24.qs")
```

```{r}
# check annotation
data$Annotation_2.0 %>% unique()
```

```{r}
# # move Annotation 2.0 to Patient 08 seurat object
# p08.data$index <- Cells(p08.data)
# #rownames(p08.data@meta.data) <- Cells(p08.data)
# data$index <- Cells(data)
# 
# Cells(p08.data) %>% length()
# Cells(data) %>% length()
# 
# p08.data.old<- p08.data
# 
# p08.data@meta.data <- right_join(data@meta.data %>% select(Annotation_2.0, index),
#           p08.data@meta.data,
#           by = "index")  
# p08.data <- subset(p08.data, cells = p08.data$index)
# p08.data@meta.data %>% nrow()
# p08.data@meta.data$Annotation_2.0 %>% head()
```

```{r}
# remove first and last 3 nucleotides from CTnt_beta
p08.data$CTnt_TRB %>% head()
p08.data$CTnt_TRB <- ifelse(nchar(p08.data$CTnt_TRB) > 6, substring(p08.data$CTnt_TRB, 4, nchar(p08.data$CTnt_TRB) - 3), p08.data$CTnt_TRB)

p08.data$CTnt_TRB %>% head()
```

```{r}
# read file containing differentially expanded clonotypes with 3 different thresholds
tcr.1013.overlap <- read.csv("/Users/gerarddeunercos/Documents/cluster1/gdeuner/SERPENTINE/data/differential_expansion_overlap_tumour/SPE08_tumour_blood_differential_1013_overlap.csv")
tcr.1865.overlap <- read.csv("/Users/gerarddeunercos/Documents/cluster1/gdeuner/SERPENTINE/data/differential_expansion_overlap_tumour/SPE08_tumour_blood_differential_1865_overlap.csv")
tcr.4015.overlap <- read.csv("/Users/gerarddeunercos/Documents/cluster1/gdeuner/SERPENTINE/data/differential_expansion_overlap_tumour/SPE08_tumour_blood_differential_4015_overlap.csv")
```

```{r}
for (id in p08.data$CTnt_TRB){
  if (!is.na(id) && id == "GCCAGCAGTTTGGTCCTAGCGGGAGGGAATAAAAAAGAGACCCAGTAC"){
    print("Found!")
  }
} 
```


```{r}
# check sequences match
unname(p08.data$CTnt_TRB) %in% tcr.1013.overlap$cdr3_nt %>% table()
unname(p08.data$CTnt_TRB) %in% tcr.1865.overlap$cdr3_nt %>% table()
unname(p08.data$CTnt_TRB) %in% tcr.4015.overlap$cdr3_nt %>% table()
```

```{r}
# modify column names of csv files
names(tcr.1013.overlap) <- c("cdr3_nt_1013", "compartment_1013", "tumour_1013")
names(tcr.1865.overlap) <- c("cdr3_nt_1865", "compartment_1865", "tumour_1865")
names(tcr.4015.overlap) <- c("cdr3_nt_4015", "compartment_4015", "tumour_4015")
```

```{r}
# merge tcr info to seurat's metadata
p08.data$cdr3_nt_1013 <- tcr.1013.overlap$cdr3_nt_1013[match(p08.data$CTnt_TRB, tcr.1013.overlap$cdr3_nt_1013)]
p08.data$compartment_1013 <- tcr.1013.overlap$compartment_1013[match(p08.data$CTnt_TRB, tcr.1013.overlap$cdr3_nt_1013)]
p08.data$tumour_1013 <- tcr.1013.overlap$tumour_1013[match(p08.data$CTnt_TRB, tcr.1013.overlap$cdr3_nt_1013)]

p08.data$cdr3_nt_1865 <- tcr.1865.overlap$cdr3_nt_1865[match(p08.data$CTnt_TRB, tcr.1865.overlap$cdr3_nt_1865)]
p08.data$compartment_1865<- tcr.1865.overlap$compartment_1865[match(p08.data$CTnt_TRB, tcr.1865.overlap$cdr3_nt_1865)]
p08.data$tumour_1865 <- tcr.1865.overlap$tumour_1865[match(p08.data$CTnt_TRB, tcr.1865.overlap$cdr3_nt_1865)]

p08.data$cdr3_nt_4015 <- tcr.4015.overlap$cdr3_nt_4015[match(p08.data$CTnt_TRB, tcr.4015.overlap$cdr3_nt_4015)]
p08.data$compartment_4015 <- tcr.4015.overlap$compartment_4015[match(p08.data$CTnt_TRB, tcr.4015.overlap$cdr3_nt_4015)]
p08.data$tumour_4015 <- tcr.4015.overlap$tumour_4015[match(p08.data$CTnt_TRB, tcr.4015.overlap$cdr3_nt_4015)]
```

```{r}
# save seurat object
#qsave(p08.data, "/Users/gerarddeunercos/Documents/cluster1/gdeuner/SERPENTINE/data/outputdata/Patient_08/Patient_08_TCR_Diff_Exp_tumor-blood_06-05-24.qs")
qsave(p08.data, "/Users/gerarddeunercos/Downloads/Patient_08_TCR_Diff_Exp_tumor-blood_06-05-24.qs")
```


