---
title: "Patient_02_SCR_C02_TCR"
author: "Gerard Deuner Cos"
date: "2024-01-11"
output: html_document
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

```{r}
# load packages
library(Seurat)
library(dplyr)
library(tidyr)
library(ggplot2)
library(scRepertoire)
library(plotly)
library(APackOfTheClones)
```

```{r}
# set up directories
work.dir <- "/Users/gerarddeunercos/Documents/SERPENTINE/"
data.dir <- paste0(work.dir, "data/")
code.dir <- paste0(work.dir, "code/")
```

```{r}
# load T Cells data
data.t <- qread(file = paste0(data.dir, "tmpdata/", "Patient_02_SCR_CO2_Tcells_subset_pp_09-01-24"))
```

```{r}
# map basic immune markers
fp <- FeaturePlot(data.t, reduction = "umap", features  = c("PTPRC", "CD4", "CD8A", "CD8B", "CCR7", "FOXP3", "MKI67", "CTLA4", "NKG7"))
fp
```

```{r}
colorblind_vector <- hcl.colors(n=7, palette = "inferno", fixup = TRUE) #plasma

DimPlot(data.t, group.by = "cloneType") +
    scale_color_manual(values=colorblind_vector[c(1,3,5,6,7)])
```

```{r}
DimPlot(data.t, group.by = "cloneType", split.by = "project") +
    scale_color_manual(values= c("darkblue", "purple", "red", "orange", "yellow"))
```

```{r}
DimPlot(data.t, group.by = "cloneType", split.by = "project") +
    scale_color_manual(values=colorblind_vector[c(2,4,5,6,7)])
```

```{r}
clonalQuant(data.t, cloneCall = "strict", chain = "both", scale = T)
```
```{r}
# APackOfTheClones Package (another way to visualize TCR clones)
DimPlot(data.t, reduction = "umap", group.by = "cluster_res1.2") + vizAPOTC(data.t)
```

